### ISSUE TITLE
Support for iframing of instances from external domain

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#108]
### Problem
WT currently uses iframes to integrate the user's selected IDE into the dashboard. However, it is not possible to iframe tale instances from non-`wholetale.org` domains. This feature is being requested for integration with a remotely-hosted service that will use the WT API along with iframes to display tale instance interfaces. Support for iframing of instances from remote domains requires (1) the ability to set custom content security policy headers and (2) the ability to customize response cookies to include the `SameSite` and `Secure` attributes. This applies not only to the the WT system but also all supported environments/IDEs.

Note: Browsers have recently deployed increasingly strict default settings for third-party cookies. Chrome (97.0.4692.71)  and FireFox (96.0.2) both require `SameSite=None` and `Secure=true` attributes on all third-party cookies and block cross-site cookies in private windows. In general, the user can configure their browser to block all third-party cookies, which may impact any solution proposed here.

### Content Security Policy
The CSP [frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) directive specifies valid parent URLs that are allowed to embed a page using `<iframe>`. WT uses the Traefik [headers](https://doc.traefik.io/traefik/middlewares/http/headers/#contentsecuritypolicy) middleware to rewrite CSPs. While default CSP values are set by the platform, it is possible to override these defaults on any newly created tale using the API by setting the `config.csp` attribute. For example:

```
{
...
    "config": { 
        "csp": "frame-ancestors 'self' https://dashboard.stage.wholetale.org https:/mapp.mydomain.org"
    } 
}
```
If not set correctly, the browser's developer console will report a CSP-related error.

### Cookies: SameSite=None and Secure=True
Browsers are increasingly restrictive about support for third-party/cross-site cookies, including those set by iframed applications. For a third-party cookie set by an iframed-application to be accepted by an up-to-date browser, it must have the `SameSite=None` and `Secure=True` attributes and the user's browser must not be configured to block third-party cookies.

As there is currently no support in Traefik to rewrite cookie attributes, each cookie-setting application will be need to be configured directly. 
* WT: The `girderToken` cookie must be set with these attributes (fixed in https://github.com/whole-tale/girder_wholetale/pull/512)
* RStudio: `repo2docker_wholetale` must be updated to add support for `www-same-site` (see  https://github.com/rstudio/rstudio/issues/6608)
* Jupyter/Lab: `repo2docker_wholetale` must be updated to set `c.NotebookApp.tornado_settings` as described in https://github.com/jupyterhub/jupyterhub/issues/3117#issuecomment-678397134
* XPRA: Does not currently set cookies
* MATLAB Desktop: Unknown

### Additional notes:
* Any application iframing a WT instance interface must provide an alternative mode of access in the event that the user is accessing via a private session or has configured their browser to block third-party cookies.
* Alternatives to this approach include (1) hosting the WT system on the local domain; (2) hosting the custom application on the `wholetale.org` domain (or DNS entry); (3) provide an alternative interface that does not use iframes.
* For `SameSite`, [two cookies are considered to have the same site when their eTLD+1 label (effective Top Level Domain; aka registrable domain) are the same ](https://stackoverflow.com/questions/59785832/samesite-cookies-frames-sub-domains-and-redirections).  This bit us when testing x.local.wholetale.org accessing instance.stage.wholetale.org.

Any IDE-specific issues are detailed in comments below.

/cc @matthew-a-dunlap

**Comment by craig-willis** [comment]
**RStudio**

When accessing RStudio via an iframe without the `SameSite`/`Secure` attributes, you may see the error `<host.wholetale.org> redirected you too many times.` In Chrome, if you open the Developer Tools, Network tab, select the first request to <host.wholetale.org> and view the Cookies tab, under Response Cookies you will see the following

```
"This Set-Cookie header didn't specify a "SameSite" attribute and was 
defaulted to "SameSite=Lax", and was blocked because it came from a 
cross-site response which was not the response to a top-level navigation"
```

![Screen Shot 2022-01-20 at 4 29 51 PM](https://user-images.githubusercontent.com/4334350/150425584-d40660b3-a4c9-4b3a-9eef-b1a4283e8761.png)

**Comment by craig-willis** [comment]
**Jupyter/Lab**

When accessing Jupyter via an iframe without the SameSite/Secure attributes, you may see the error `<host.wholetale.org> refused to connect`. In Chrome, if you open the Developer Tools, Network tab, select the first request to <host.wholetale.org> you may see the request has status `(blocked:other)` and viewing the Cookies tab, under Response Cookies you will see the following:

```
This Set-Cookie header didn't specify a "SameSite" attribute and was 
defaulted to "SameSite=Lax", and was blocked because it came from a 
cross-site response which was not the response to a top-level navigation
```

![Screen Shot 2022-01-20 at 4 43 51 PM](https://user-images.githubusercontent.com/4334350/150426945-af700330-ddbb-4100-82cb-00b7c7b5e035.png)

**Comment by Xarthisius** [comment]
R/Jupyter are done, I haven't tried matlab yet. Reopening for now.

**Comment by Xarthisius** [comment]
I've checked Matlab desktop and it works out of the box.
