### ISSUE TITLE
Problems with Creating New Tale

### ISSUE THREAD

**Issue by WardLT** [whole-tale/whole-tale#12]
I'm running into a some problems when trying to create Tales:

- I can't seem to select folders in the "Data" step. During the data step, I click on "Data" and see the folder I want to add to my Tale but no way to indicate that is the folder I want. When I get to the "Create" step, I have a warning text saying "Folder Not Chosen" (screenshot below).

- The system hangs on "Saving The Whole Tale" when I click submit on the "Create" step? I have a loading bar at the bottom that hasn't gone away after a few hours.

![image](https://user-images.githubusercontent.com/7003149/31677747-644426e0-b331-11e7-9f2e-cd167cb52cb5.png)

**Comment by ThomasThelen** [comment]
We've since re-factored the compose page and have completely changed the way that user's select data. We haven't seen any reports of this behavior in the new system so I'm going to close this.
