### ISSUE TITLE
Stata 17 Jupyter environment fails on build

### ISSUE THREAD

**Issue by amichuda** [whole-tale/whole-tale#128]
**Steps to Reproduce**

Start a whole tale environment with Stata 17 Jupyter

**Expected Results**

The whole tale builds

**Actual Results**

There is a build error having to do with `Dockerfile parse error line 184: Unknown flag: mount`
 
Please let me know if I'm doing something wrong here! I'm not adding any files to the environment before running the tale.

**Comment by craig-willis** [comment]
Thanks for reporting this issue.  We just moved to new hosting infrastructure and it looks like I missed a configuration setting.   I'm testing now  and will update this issue when I've confirmed its working.

**Comment by craig-willis** [comment]
I've confirmed that I'm able to build and run a Stata 17/Jupyter environment. Let me know if you encounter any further issues.

**Comment by amichuda** [comment]
Thank you!

**Comment by amichuda** [comment]
Can confirm that it builds now, thank you!
