### ISSUE TITLE
Cannot add a folder in Tale Workspace

### ISSUE THREAD

**Issue by amichuda** [whole-tale/whole-tale#129]
**Steps to Reproduce**

Start a new Tale and go to "Files" Tab. Press the "+" button.

**Expected Results**

There would be an "Add Folder" option or I would be able to add a folder with "Add file"

**Actual Results**

I cannot do that.

Despite it saying that I can "add a folder," none of the options, let me. Please let me know if I'm missing something!

**Comment by craig-willis** [comment]
<img width="1084" alt="Screen Shot 2022-07-19 at 12 05 11 PM" src="https://user-images.githubusercontent.com/4334350/179797378-48f6024d-53db-4438-9c9a-cb16f69b5d25.png">
Do you see the menu as above under the "Tale Workspace"?  You should be able to "Create Folder" or "Upload File" (you can also do these things from within Jupyter, once started).

Feel free to join the [Whole Tale Slack ](https://join.slack.com/t/wholetale/shared_invite/enQtNDM1OTg2ODU5MzUxLWJmZTg2MDQyOGNlYzY0ODZmYmFiN2ExZTI0NmZlMzZiZDFiNjU3MTFiYTZhODQwMDNlNTBjZGZhZWY0ZjFkZTk) #general channel if you'd like.

**Comment by amichuda** [comment]
Ah! I see. But can I upload a whole folder all at once?

**Comment by craig-willis** [comment]
Unfortunately not with the current production release. Uploading folders has been 
implemented in https://github.com/whole-tale/ngx-dashboard/pull/268 and will be included in the next release (date TBD). In the meantime you can either (1) use features of Jupyter or (2) upload/extract a zip archive from within Jupyter.

**Comment by amichuda** [comment]
> upload/extract a zip archive from within Jupyter.

Duh, that's a perfect workaround, sorry for that!
