### ISSUE TITLE
Cannot remove a tale

### ISSUE THREAD

**Issue by veroandreo** [whole-tale/whole-tale#153]
**Steps to Reproduce**

I log in, go to my tales, try to remove [this one](https://dashboard.wholetale.org/run/64388157b3b74e434bd8f1ac?tab=metadata), click on `confirm`, but nothing happens. Tale is not removed as requested, even trying several times.

**Expected Results**

That the tale is indeed removed.

**Actual Results**

The Tale is not removed

**Comment by Xarthisius** [comment]
There was an issue with nfs backend that I've just fixed. Could please try again?

**Comment by veroandreo** [comment]
Yes, now it worked. Thanks for such a prompt response and fix! :rocket:
