### ISSUE TITLE
Can't create new folder

### ISSUE THREAD

**Issue by matthewturk** [whole-tale/whole-tale#16]
I'm on https://dashboard.wholetale.org/upload and I've selected "Home" and I can't create a new folder.

**Comment by MatthewTurk** [comment]
If I navigate away, then back, and click on New Folder, it lets me -- but the *top* dialog is the one that works, and a second, slightly vertically-offset dialog does not.

**Comment by MatthewTurk** [comment]
![wt_bug1](https://user-images.githubusercontent.com/89019/35408479-e014acb2-01d4-11e8-9c37-90c636aeb13f.png)

**Comment by ThomasThelen** [comment]
This page has been depreciated and needs to be removed from the codebase (see linked issue). Closing.
