### ISSUE TITLE
LIGO Tale stalls early?

### ISSUE THREAD

**Issue by ludaesch** [whole-tale/whole-tale#18]
I'm running one of the pinned tales (LIGO tutorial) in the dashboard.
Under "Cell", I hit "Run All" and the tale stops at Step 2:
ModuleNotFoundError: No module named 'scipy'

Now what?

<img width="1333" alt="2018-02-13_0934-wt-ligo-error" src="https://user-images.githubusercontent.com/7769871/36158252-805bf81c-10a1-11e8-8c19-db1c4c74ea33.png">

**Comment by Xarthisius** [comment]
I believe it's now fixed. Please try again.
