### ISSUE TITLE
Pre-Run Usability Tests (developers)

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#20]
Initial usability testing based on draft:
https://hackmd.io/d-m0LsVXSh2EpzhcRJMCUA

* Collect responses from all developers
* Distill into unstructured document for analysis
* Define process for handling output -- i.e., getting PI/stakeholder feedback and deciding what to act on
* Refine the usability test based on internal feedback
* Create issues based on things we decide we want to change for MVP

Q. What would we change for MVP?
Q. What would we change about the usability test?

**Comment by craig-willis** [comment]
@Xarthisius Should we call this done?

**Comment by craig-willis** [comment]
Per discussion, will link http://wholetale.readthedocs.io/development/testing/Usability_Test_Results.html  in documentation TOC

**Comment by craig-willis** [comment]
Added TOC entry under developmen/testing

http://wholetale.readthedocs.io/development/testing/index.html

**Comment by Xarthisius** [comment]
Thanks!
