### ISSUE TITLE
Define format for packaging/serialization of a Tale

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#24]
This is the first draft of the serialization format. Ideally, we can get broader stakeholder support through Working Groups

Completion criteria
* Design document/review
* Working group feedback

**Comment by amoeba** [comment]
Started filling this on in https://github.com/whole-tale/wt-design-docs/commit/a5eb7cd055d2b713af0085fd6ea077c7160ec369. Far from done.

**Comment by nuest** [comment]
I follow your project with high interest! Maybe you've heard about [o2r](http://o2r.info/results), too.
Just wanted to point out that we're working on something similar as "Tales", we call it "executable research compendia" (ERC). Find the current draft of a specification at [http://o2r.info/erc-spec/spec/](http://o2r.info/erc-spec/spec/). Hope it helps, feedback is of course welcome!

**Comment by Xarthisius** [comment]
Hi @nuest ! ERC looks very interesting! I'll take a look to see if we can leverage your work. I also took a liberty of forwarding your comment to other members of the project that may not be following discussions on pull requests closely.

**Comment by mbjones** [comment]
Yes, thanks for the pointer, @nuest.  ERC looks really interesting.  There are a *lot* of packaging formats in development.  The tend to fall into several groups, and our DataONE packaging format is in the ORE manifests with BagIt group.  There's another group around using JSON manifests.  

A pretty extensive list is being developed here (https://docs.google.com/document/d/155lA2BcixTl-zwJHGfLkxsmg7WmQbBK00QWyP8QggkE/edit) with the goal of using RDA as a mechanism to get some degree of community consolidation.  That list shows at least 18 and possibly more than 25 actively used formats, depending on how you slice it.  I just added ERC to that list, so please correct anything I got wrong.

So, lots to consider.  Given that many of our affiliated repositories have adopted the DataONE data packaging format, that is the simplest approach for us. However we do it, I think the data archival packaging format and the 'active' packaging format should be the same -- they are all just containers for metadata and digital objects.

**Comment by amoeba** [comment]
Hey @nuest thanks for chiming in. ERC sets out to do a lot of the same things we'll be wanting to do so that's super helpful to know about it.

@mbjones thanks for the link to that list.

**Comment by craig-willis** [comment]
@amoeba Per discussions with @mbjones last week about the [v0.5 draft specification](https://docs.google.com/document/d/1adfF2Yy9-khVemZRhc3_v_MJzLyI8bnVdJkNon0WZ1Q/edit?usp=drive_web&ouid=100483385319264097097), it sounds like we want to extend this task to also include:

* Reconciling with RDA packaging initiative
* Documenting specification (likely through updating the readthedocs pages)

Once we have a final version of our internal format, we can close this and open a follow-up to address any feedback from your RO meeting.
