### ISSUE TITLE
When creating a tale I get many instances of the tale on the browse page

### ISSUE THREAD

**Issue by kylechard** [whole-tale/whole-tale#28]
Also, I can start each instance of the tale, but they seem to spin forever. 

![image](https://user-images.githubusercontent.com/793984/42780428-c09aa1f0-8908-11e8-977d-342122ca3ae4.png)

**Comment by ThomasThelen** [comment]
I'm unable to reproduce this behavior; we've had quite a few UI changes since the creation of this issue. If no one else can reproduce this, we can probably close this issue.

**Comment by ThomasThelen** [comment]
I'm still unable to reproduce this, closing.
