### ISSUE TITLE
Common DataOne and Globus Authentication mechanism

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#31]
We still do not have a solution for the DataONE/Globus integration.  For publish we are using a popup to login the user via DataONE/ORCID.

**Comment by ThomasThelen** [comment]
An agreement on whose certificate was to be trusted (does Globus trust DataONE vs DataONE trusting Globus) was never reached between Globus and DataONE; As a result Whole Tale now has the 'Account Settings` page that allows users to connect to either services, disjointly. I'm assuming that we're no longer pursuing the common authentication and that this can be closed.

**Comment by craig-willis** [comment]
Agreed. We have looked into requiring ORCID as part of the Globus flow. But this can be closed and new issues filed when we decide to address.
