### ISSUE TITLE
Tales missing images

### ISSUE THREAD

**Issue by kylechard** [whole-tale/whole-tale#33]
On the main browsing page two tales have broken image links.  I have cleared cache and these links still don't load. Is there a way we can store images used for tales somewhere so that we don't end up with broken links?

![image](https://user-images.githubusercontent.com/793984/44053380-1b7df614-9f05-11e8-93cd-e7e57350b4b0.png)

**Comment by Xarthisius** [comment]
It's fixed. Thanks for the report!
