### ISSUE TITLE
Document working groups and formation process

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#37]
As a WT collaborator, I would like more information about past/present working groups including membership, status, activity, and outputs.  I would also like information about how to propose new working groups.  

* [x] Update wholetale.org with background information about working groups: https://hackmd.io/a9KkXNQ9QzarEiFmFKWUjw
* [x] Update https://github.com/whole-tale/whole-tale (or other public space) to include basic information about all current or past working groups including chairs, members, status, activity, and outputs
* [x] Define the process for forming new working groups

**Comment by kylechard** [comment]
Could we update the materials science WG link to the github repo. I moved most of our content over there.

**Comment by craig-willis** [comment]
Sorry I missed that @kylechard. Should be done now.
