### ISSUE TITLE
XSEDE allocation request

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#41]
> XSEDE is now accepting Research Allocation Requests for the allocation period, January 1, 2019 to December 31, 2019. The submission period is from September 15, 2018 thru October 15, 2018. Please review the new XSEDE systems and important policy changes (see below) before you submit your allocation request through the XSEDE User Portal

We are still operating on an oft-renewed startup allocation.  This is an opportunity for us to apply for real resources for 2019.

**Comment by Xarthisius** [comment]
Proposal submitted

```Request Title: Merging Science and Cyberinfrastructure Pathways: The Whole Tale
Request Number: ASC180056
PI Name: Kacper  Kowalik
Action Type: New
Allocation Type: Research
```
