### ISSUE TITLE
Initial meeting of Open Science Infrastructure WG

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#43]
The [Open Science Infrastructure WG](https://github.com/whole-tale/whole-tale/tree/master/working_groups/open-infrastructure) was pitched at the [Workshop on Tools and Approaches for Publishing Reproducible Research](https://wholetale.org/2018/06/26/working-group-workshop.html) and there was interest in further discussion from representatives from eLife, DataONE, DataLad, and Dataverse.

I'm proposing the first of what I hope will be regular calls coordinated by the WT project.  This will be an open call, with the initial goal of enabling participation from potential collaborators across a number of timezones (NZDT, PDT, CDT, EDT).   If this works out, we'll adjust the next call to be friendly to other timezones.

**Wednesday October 24, 2018, 1pm PDT/4pm EST and 9am NZDT (via Google Meet)**

Details:
* https://meet.google.com/czh-fknp-jmm
* ‎(‪US‬) ‪+1 724-260-6039‬
* PIN: ‪337 776 853#‬

Tentative agenda:
* Brief introduction of participating projects, motivated by @npscience's diagram below and proposal to explore full-stack domain verticals through all of these environments
* Identify points of potential interoperability and/or collaboration  across projects. Per suggestion below, including a list of potential discussion points https://docs.google.com/document/d/1bOVWBfhOiKGU2dYoHN_Pkpv5zPI6y819UISfkTqYpoQ/.  Please feel free to edit or suggest changes 

Data repository/Platform/Publisher: Reproducible Research Publishing and Interoperability

![datarepo-platform-publisher 2f 2f reproducible research publishing interoperability](https://user-images.githubusercontent.com/4334350/46379005-0e5f7900-c663-11e8-89df-4b06a62f51e0.png)

**Comment by craig-willis** [comment]
My first attempt to coordinate a meeting via Github, we'll see how it goes:

@aculich @pdurbin @jonc1438 @npscience @nuest @choldgraf @Xarthisius

**Comment by npscience** [comment]
Shared link with Substance and Stencila folks

**Comment by yarikoptic** [comment]
FWIW can make it, marked calendar

**Comment by jonc1438** [comment]
Sorry my October early Nov is bad. I am in Africa from Oct 22- Nov 10th

**Comment by cboettig** [comment]
This sounds exciting, and I'd be interested in joining the call as well, if that's all right.  For those I haven't met: I'm an ecologist who tries to publish reproducible workflows (a la binder, R compendia) and a maintainer of the Rocker project Docker images, which I believe can be used by binder and WholeTale.

**Comment by craig-willis** [comment]
@jonc1438  sorry to miss you, but hopefully we connect about your [CoRe2](https://odum.unc.edu/2018/07/alfred-p-sloan-foundation-grant/) award and other topics after you return.  I expect to hold several of these calls, if useful.

@cboettig I was hoping to meet you at the Chicago workshop and am glad you saw this.

**Comment by pdurbin** [comment]
@craig-willis @Xarthisius @npscience it was great meeting you in Chicago. Thanks for listening to my "Dataverse and Reproducibility" talk ([slides](https://twitter.com/philipdurbin/status/1040267883090202625), [video](https://www.youtube.com/watch?v=SuyQTsOGugc)), which (spoilers!) featured @jonc1438 and @aculich 😄 

That specific time might be challenging enough that I'd only be able to attend the first half but perhaps @scolapasta @djbrooke @mercecrosas or others from @IQSS could represent Dataverse. I **could** even invite the Dataverse community via our mailing list, if you're cool with that. I don't know how many people you want or how many would call in.

**Comment by craig-willis** [comment]
Thanks much, @pdurbin.  Whether on this call or another, I look forward to hearing more about the [Sloan award](https://www.iq.harvard.edu/news/sloan-grant-awarded-iqss-dataverse-data-sharing-project) and integration with CodeOcean/Encapsulator.  While I do lean toward a smaller group for the initial call, it will be open -- so I leave it to you.

**Comment by nuest** [comment]
I'd be interested to join, too!

I've been working in the o2r project (https://o2r.info/about) on connecting container-based (Rocker) reproducible research with a reading/publishing/review workflow, see http://o2r.info/architecture/ I guess our approach is somewhere between Stencila and WholeTale, with 5 % of the manpower :muscle: :wink: and a focus on geospatial analysis (maps etc.).

**Comment by craig-willis** [comment]
@nuest  -- glad to hear it. Your name came up at the workshop.  We've looked at o2r based on your [comment about our format specification](https://github.com/whole-tale/whole-tale/issues/24#issuecomment-371877434) and I know that we've crossed paths on the Binder gitter [talking about `repo2docker` for DataONE, Dataverse, and Zenodo](https://gitter.im/jupyterhub/binder?at=5b7d47b1f5402f32aa763765).

**Comment by craig-willis** [comment]
@betatim -- may be of interest (or future call, as timezone is likely inconvenient)

**Comment by aprilcs** [comment]
I'd love to join too, if possible. 😄

**Comment by choldgraf** [comment]
Hello from Jupyter/Binder land 👋 looking forward to chatting with you all about this stuff.

A quick thought from my perspective: I think it's better to break "Binder" into a few sub-components. The tech under the hood is designed to be modular in a way that lets each piece be used separately, if need be. Here are the main pieces:

* [repo2docker](https://repo2docker.readthedocs.io/en/latest/) turns a github repository into a Docker image. Is both language- and interface-agnostic. (e.g. we use it at Berkeley to build RStudio images for classes)
* [JupyterHub on Kubernetes](http://z2jh.jupyter.org) spawns jupyter servers (user sessions) on Kubernetes that serve a Docker image.
* [BinderHub](https://binderhub.readthedocs.io) provides a UI that lets users spawn a repo2docker process that builds a repository they host online (e.g. github), then spawns a JupyterHub user server that serves that image (also on Kubernetes)

Each of these pieces are separate from one another + open source. The deployment at https://mybinder.org is just one instance of a BinderHub server, but it's meant to be deployed anywhere that runs Kubernetes (e.g. the [Pangeo project runs their own binderhub server as well](http://binder.pangeo.io/))

Hope that clarifies some things!

**Comment by craig-willis** [comment]
Thanks @choldgraf -- I know I've conflated the components as I've tried to understand them.

Curious -- has there been any discussion about separating out "binders" (is that the right term for the formatted repo?) or BinderHub as an API/interface independent of the specific implementation?  WT is strongly considering moving to repo2docker internally. It would be a longer term goal to run BinderHub itself, but it might be possible to support a BinderHub-compatible interface to support access to specialized resources.

**Comment by choldgraf** [comment]
hey @craig-willis, could you go into a bit more detail on what you mean by "independent of the specific implementation"?

**Comment by betatim** [comment]
In repo2docker we started this thread discussing what to do beyond the standard files for specifying dependencies [here](https://github.com/jupyter/repo2docker/issues/386).

The idea of a YAML file that specifies compute resources required, version of repo2docker to use or datasets to mount has been suggested a few times. It would need someone to drive that discussion forward to find an existing standard that can be adopted, wrangle all the technical pros&cons, etc.

> it might be possible to support a BinderHub-compatible interface to support access to specialized resources

Could you explain a bit what the user story is for this to help me understand your sentence? I can't quite picture what this would be like in practice.

**Comment by craig-willis** [comment]
Thanks @betatim -- I wasn't aware of that issue (and sorry for the unclear question).  

The context for the question (and this WG) is potential interoperability between existing systems and particularly through the publication pipeline.  I'm thinking not only about reproducibility environments (e.g., WT, CodeOcean, etc) but also the various systems out there that let you run containers near specialized data or compute resources (e.g., SciServer, Labs Workbench, yt.Hub, etc).

Use case (my goto [TERRA-REF](http://terraref.org/)): _Researcher A publishes a paper describing a new method of calculating crop canopy height from drone data linked to a binder repo that's been deposited in Dataverse. Researcher B discovers the paper and binder and wants to explore application of the method to the TERRA-REF reference dataset. The 2PB dataset is hosted at NCSA and available for interactive analysis via containerized environments using the Platform X. (Platform X is one of a number of systems that support the BYO container model to specialized data or compute resources)._

There are a few ways to support this scenario:
* Research B manually sets up a similar environment in Platform X using information from the published binder (i.e., builds a Dockerfile or runs repo2docker to push/tag an image that they can run).
* The TERRA-REF project installs the full BinderHub stack next to the data
* Platform X is extended to support repo2docker and optionally expose capability via the [BinderHub API ](https://binderhub.readthedocs.io/en/latest/api.html#) to provide a consistent experience for users.

The first part of my question was really about the binder repo format as a standalone packaging format that could be used/imported by other systems -- similar to WT Tales or CodeOcean Capsules.  Per your comment, it sounds like there has been discussion about this as well as [what needs to be captured](https://github.com/jupyter/repo2docker/issues/170) for longer-term reproducibility.

The second part of my question is about systems that might want to support running binders but where it might be impractical to adopt/integrate the full BinderHub stack.   They could potentially adopt repo2docker and expose the capability via something like  the BinderHub API.  My original vague question was whether you've had any discussions about something like this.

**Comment by choldgraf** [comment]
@craig-willis this is great context, thanks!

I think that, in general, we in Jupyterland are a big +1 on open standards, so I like the idea of agreeing on a general repository structure, configuration file, etc. (e.g. we've discussed for a while now that having a `binder/` folder is too binder-specific for our tastes).

**Comment by michael** [comment]
Nice agenda!

I can't promise (as I'll be travelling that date) but will try to make it.

**Comment by betatim** [comment]
Could you make "Identify points of potential interoperability across projects" more concrete maybe with some specific questions?

From Binder-land we will struggle to have someone who can join in real-time but can send some written words if we create some concrete questions or points of discussion. This would probably also help everyone else attending the meeting in person as people could prepare and did not have to think of replies on the spot.

**Comment by craig-willis** [comment]
@betatim A fair request. My plan was to use the initial call to drive such a list of questions or points of discussion based on group interest, but I can certainly pose some that we can refine in advance.  My goal was to bring interested folks together and coordinate a discussion -- I don't pretend to understand all of the aspects of the participating projects that might be of interest.  Also, after further thought, I'd like to change "interoperability" to "interoperability and/or collaboration."

I've drafted the following list based on discussions from the Workshop as well as related side discussions with Jupyter/Binder and Dataverse.  

https://docs.google.com/document/d/1bOVWBfhOiKGU2dYoHN_Pkpv5zPI6y819UISfkTqYpoQ/

Please feel free to suggest additional questions or ways that I could improve the structure/content.
Note that the Workshop discussions centered around groups that were present -- WT, eLife (Stencilia/Substance by association), Dataverse, DataONE.

The list is obviously too large for a single introductory meeting, but we can prioritize based on interest and who joins the call.

**Comment by choldgraf** [comment]
Cc @davclark who works with the gigantum project and would probably be interested in this call too

**Comment by jonc1438** [comment]
Craig,

Unfortunately I will be traveling in Africa and not able to attend. Don Sizemore will attend for me.
Can you add him to your email list

Thanks

Jon


Jonathan Crabtree
Assistant Director for Cyberinfrastructure
HW Odum Institute for Research in Social Science
www.odum.unc.edu
Jonathan_Crabtree@unc.edu
919-962-0517 Office
919-428-6112 Cell

**Comment by craig-willis** [comment]
@jonc1438 Glad to hear @donsizemore can join. Most communication is coming through this github issue -- I don't actually have emails for most of the people here.

**Comment by craig-willis** [comment]
Updated issue description with Meet information.  Please feel free to contact me at willis8@illinois.edu if you have any questions.

**Comment by choldgraf** [comment]
For those in this thread who got auto-notified of the last post and were just like "oh shit is that meeting today?!?!?!" no, it is not, it's tomorrow :-)

**Comment by craig-willis** [comment]
Thanks @choldgraf and sorry for any confusion!  I had some email requests to add folks to the Meet invite and thought it was a good time to advertise.

**Comment by nuest** [comment]
@sje30 fyi, see [notes doc](https://docs.google.com/document/d/1bOVWBfhOiKGU2dYoHN_Pkpv5zPI6y819UISfkTqYpoQ/edit#)

**Comment by craig-willis** [comment]
Thank you all for participating -- I really enjoyed the discussion! For those that weren't able to attend, notes from this initial call are at the bottom of the [agenda document](https://docs.google.com/document/d/1bOVWBfhOiKGU2dYoHN_Pkpv5zPI6y819UISfkTqYpoQ/edit#) linked above.  

We will be arranging a follow-on call in ~1 month, likely again via Github (see note below).  As discussed, I will likely split out training/outreach discussions into a separate call around the budding [EOT Working Group](https://github.com/whole-tale/whole-tale/tree/master/working_groups/education).

Please feel free to add any thoughts/suggestions for how to improve the next call (organization, communication, etc) to the notes document or email me directly (email in notes).

**Comment by craig-willis** [comment]
For those interested, I wanted to highlight from @pdurbin's comment in the notes document:

>  The Dataverse Community Call this week included representatives from Code Ocean and you can see the notes from that call at https://groups.google.com/d/msg/dataverse-community/HPLziKZbOAc/q_XEqyKEBwAJ

**Comment by jbpoline** [comment]
Thanks - this is great !

**Comment by amoeba** [comment]
I ran into @joeklieg at IEEE eScience last week and he's working on https://nextjournal.com/ which seemed very relevant to this call. @craig-willis 	could you please add Joe to the call list?

**Comment by joeklieg** [comment]
@amoeba - thanks for the invite!
@craig-willis I would love to participate in this group. Nextjournal is in the same ecosystem as WT, Binder, Code Ocean and we would love to work together.

**Comment by craig-willis** [comment]
Closing this and opening https://github.com/whole-tale/whole-tale/issues/50 to propose a second call.
