### ISSUE TITLE
Typo: "wholetalae" mailing list on "participate" page

### ISSUE THREAD

**Issue by pdurbin** [whole-tale/whole-tale#46]
https://wholetale.org/participate.html has a typo ("wholetalae") saying "Join our mailing list to keep up with updates and new features https://groups.google.com/forum/#!forum/wholetalae"

<img width="1133" alt="screen shot 2018-10-11 at 8 01 17 am" src="https://user-images.githubusercontent.com/21006/46802701-1175fb80-cd2c-11e8-9ac1-be53f700b17e.png">

<img width="1133" alt="screen shot 2018-10-11 at 8 02 45 am" src="https://user-images.githubusercontent.com/21006/46802700-1175fb80-cd2c-11e8-9a2f-e39c22e6a5ed.png">

There does seem to be a mailing list with light traffic at https://groups.google.com/forum/#!forum/wholetale

**Comment by Xarthisius** [comment]
Thanks @pdurbin ! Fixed in https://github.com/whole-tale/whole-tale.github.io/commit/b0f027bcad4884ba676fae89422d5aba65a9bdf2

**Comment by pdurbin** [comment]
Thanks! I would have made a pull request myself but I couldn't find the repo quickly. Next time. 😄
