### ISSUE TITLE
2nd Open Science Infrastructure WG call

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#50]
Following on from the successful [initial discussion](https://github.com/whole-tale/whole-tale/issues/43), I'd like to propose a second call for:

**Wednesday November 28, 2018, 10am PT/1pm EST (via Google Meet)**

Details:
* https://meet.google.com/czh-fknp-jmm
* US +1 724-260-6039‬
* PIN: ‪337 776 853#‬

Per @nuest's suggestion, I propose that this call serve as a sort of showcase of the different tools and platforms.  I'd like to encourage demonstrations of use cases that show/suggest integration between the different projects represented on the call.

I've put a [tentative agenda](https://docs.google.com/document/d/1bOVWBfhOiKGU2dYoHN_Pkpv5zPI6y819UISfkTqYpoQ/edit#) in the original shared notes document:

* Brief introductions
* Short platform/use case demonstrations
* Discussion of interoperability/collaboration opportunities

I've also drafted a few ideas of things I'd like to see based on the previous call, but please feel free to comment/edit/delete as you see fit.

**Comment by craig-willis** [comment]
I'm still not sure whether I should be doing this via Github, but I'm adding explicit mentions to make sure folks at least aware that this has been scheduled for next Weds 11/28. Feedback on the agenda (linked in description) welcome.

@aculich @pdurbin @npscience @nuest @choldgraf @Xarthisius @yarikoptic @jonc1438 @cboettig @betatim @choldgraf @jbpoline @donsizemore @tlchristian @sje30 @amoeba @joeklieg @aprilcs

**Comment by yarikoptic** [comment]
Add a team (e.g. open-science-wg) on whole-tale organization [settings](https://github.com/organizations/whole-tale/settings/teams), invite/add us to that team, mention the team here (@whole-tale/open-science-wg) ?

**Comment by choldgraf** [comment]
cc @davclark as I didn't see him on the list of original pings!

**Comment by nuest** [comment]
Hi! Unfortunately I could attend today's call. Here's a quickly recorded demo of our current state. It shows

- How to create an ERC from an example R Markdown-based "workflow" loaded from a public owncloud share
- How to edit/complete metadata during creation, and see the different created formats
- How to start an execution, which ends with a "check" including a visualisation highlights differences between the author submitted display file and the result created by the service
- You can also "substitute" a specific files from one ERC with a file from another, which allows for rudimentary data exchange. We utilise container mounts, IMHO it's a nice way to transparently re-combine analysis (no, we have not even dared to think about how incompatible data structures could be handled)

**http://nuest.staff.ifgi.de/o2r-features-demo-2018.gif**

Other features not shown: we have implemented storing and loading from Zenodo, as in [our context definition](https://o2r.info/architecture/#31-business-context) the reproducibility service has "no storage", and manipulation ([see preprint](https://doi.org/10.31223/osf.io/jtd8c)).

Really sorry to miss out on the call - hope to join again next time.

**Comment by craig-willis** [comment]
Sorry to miss you @nuest and thank you for the demo link and details.

Thanks to everyone who joined the call and for the demonstrations! As mentioned, I will schedule a follow-up in January.  Since we ran out of time, we'll need to work on the agenda asynchronously.

Notes from today's call are in the same  [notes and agenda document](https://docs.google.com/document/d/1bOVWBfhOiKGU2dYoHN_Pkpv5zPI6y819UISfkTqYpoQ/) .  We had demonstrations of DataLad, Dataverse external tools integration including examples from Whole Tale and Binder, Nextjournal and a walk-through of the [Odum archives verification workflow](https://drive.google.com/file/d/1W4gdckYXh9fANLdTloTydJRGtb2E9PMl/view). @davclark pointed us to a [video demonstration of Gigantum](https://www.youtube.com/watch?v=S4oW2CtN500).

For future scheduling, if you put your email address in the [notes from today's call](https://docs.google.com/document/d/1bOVWBfhOiKGU2dYoHN_Pkpv5zPI6y819UISfkTqYpoQ/), I will include you in a calendar invitation but will also continue to mention via Github.

**Comment by aculich** [comment]
@craig-willis thanks for organizing, and wish I could have joined for longer! I'll plan to join the next one more fully (and a calendar invite will help with that!)

Also, including @maryamv on this thread to loop her into the discussion and future calls that we have.

**Comment by craig-willis** [comment]
Victoria Stodden shared a link William Jacoby's (editor AJPS) presentation to the National Academies of Science Committee on Reproducibility and Replicability in Science from December 2017.  Nice mentions of Harvard Dataverse and Odum's work with AJPS for sure!

http://sites.nationalacademies.org/DBASSE/BBCSS/DBASSE_184240
