### ISSUE TITLE
Custom environments

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#51]
[Custom Environments](https://docs.google.com/document/d/1lZiHXYfqRaDrfjOXHW5j3g9OUrhc0wm8_cX0QgGDLLk/edit#) design document.

Users must be able to configure custom environments for Tales through the addition of packages via common package managers (e.g., OS, pip, Conda, R, etc). Users must be able to rebuild the underlying image and update running instances to use the newly built image.

**Comment by Xarthisius** [comment]
Done and released
