### ISSUE TITLE
404 when following info to sign in from the dashboard entry

### ISSUE THREAD

**Issue by datadavev** [whole-tale/whole-tale#54]
Visiting https://dashboard.wholetale.org/login when not logged in, there's a link under "Login questions" for "Signing In".

The link points to a non-existent page:

  https://wholetale.readthedocs.io/users_guide/sign_in.html 

which should probably be:

 https://wholetale.readthedocs.io/en/stable/users_guide/sign_in.html

**Comment by Xarthisius** [comment]
@datadavev Thanks for the report! New version with fixed urls should deploy within next hour. I think you'll need to refresh the browser cache in order to see the changes.
