### ISSUE TITLE
Rstudio Home breadcrumb is confusing

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#57]
Noted by @ian-taylor  on 1/7 dev call, the "/Home/work/home" structure in Rstudio is confusing. This 
has been noted before on Slack.

<img width="429" alt="screen shot 2019-01-07 at 2 24 16 pm" src="https://user-images.githubusercontent.com/4334350/50791602-f281f980-1287-11e9-99b2-3eb79265c5fd.png">

Per https://wholetale.slack.com/archives/G3QBV6QDC/p1539372688000100, Rstudio cloud has changed this value:
<img width="190" alt="screen shot 2018-10-12 at 11 30 29 am" src="https://user-images.githubusercontent.com/4334350/50791396-53f59880-1287-11e9-9db2-f334cf903fa5.png">

**Comment by Xarthisius** [comment]
![breadcrumbs](https://user-images.githubusercontent.com/352673/50931306-d2893c00-1427-11e9-9562-818d438edb48.png)

How about that ^^ ?
