### ISSUE TITLE
Copy on Launch

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#62]
A user with read-only access to a Tale must be able to run the Tale and modify the contents without impacting the primary copy.  We call this feature "copy on launch"  -- each user will get a read-write copy of any read-only Tale they try to launch.

There are three distinct use cases with different problems:
* User A wants to modify user B's tale:  User A needs a copy of the workspace to modify it.  This is the primary case for "Copy on Launch."
* User A wants to only run user B's tale: The main problem here is if results are written to the workspace, the Tale will fail of filesystem is read-only. This suggests the need for a "results" or similar output directory
* User A wants many students to run example/tutorial tale:  Ideally, the tale would be runnable with read-write output, but still referencing the same workspace. This way, the instructor can update the code without requiring students to restart.

See also 9/2018 AHM notes and [Tale Workspace design](
https://docs.google.com/document/d/1pl9FwVNeXyVVTccXLoTIeXsViWflbPpoQ5DLY44g5cw/edit) document.

**Comment by ThomasThelen** [comment]
This has been completed. We now display a dialog to a user asking if they'd like to create a copy of the original Tale. This was completed in 0.7 or 0.8
