### ISSUE TITLE
Error message appears when trying to move to public workspace

### ISSUE THREAD

**Issue by samwalkow** [whole-tale/whole-tale#64]
When trying to access a public workspace I got an access error message.
![Screen Shot 2019-03-14 at 9 58 11 PM](https://user-images.githubusercontent.com/38114494/54405879-faa24f00-46a5-11e9-87fa-d4256d7d8133.png)
![Screen Shot 2019-03-14 at 10 03 34 PM](https://user-images.githubusercontent.com/38114494/54405890-055ce400-46a6-11e9-90c2-f3cea7401758.png)
![Screen Shot 2019-03-14 at 10 03 56 PM](https://user-images.githubusercontent.com/38114494/54405898-0726a780-46a6-11e9-9b95-699c864d4cf6.png)

**Comment by Xarthisius** [comment]
@samwalkow I'm afraid that's expected. "Public" doesn't mean you can modify content of an object or space. In this case the Tale Workspace your trying to move files from belongs to @MatthewTurk, not you. In this case you can only copy that data.

FTR:
folderId: `5c8b129a2744a50001c5e50c`
folder_path: `/collection/WholeTale Workspaces/WholeTale Workspaces/5c8b129a2744a50001c5e50c`
taleId:  `5c8b129a2744a50001c5e50c`

**Comment by samwalkow** [comment]
Got it! To collaborate with Matt on a workspace, do I copy his workspace then?

**Comment by Xarthisius** [comment]
I'd need to understand what you mean by "collaborate"

**Comment by samwalkow** [comment]
How can I (or Matt) make changes to a workspace, or a notebook, and have the other see the changes or have access to that notebook?

**Comment by Xarthisius** [comment]
In the current WT version (v0.6) you can only modify the content of the workspace that you own. Other people will be able to see it (readonly). Unfortunately, joint curation of content by two or more collaborators is not possible yet.

**Comment by samwalkow** [comment]
Ok got it! Also, the changes to the interface look great. It's much easier to navigate around my tale.

**Comment by MatthewTurk** [comment]
@Xarthisius To be honest I'd have expected the error message -- which does make sense, I get why it throws it -- to be wrapped in some type of notice.
