### ISSUE TITLE
Make footer collapsible

### ISSUE THREAD

**Issue by matthewturk** [whole-tale/whole-tale#67]
The footer is cool and necessary, but on smaller-ish screens, being able to collapse it would free up a not-inconsiderable amount of real estate.  A box to close it would work, but then would get rid of "report a problem" which I don't think would be good to do.

**Comment by Xarthisius** [comment]
The only reason it's there is for 1) NSF ack, 2) reporiting issues. If we can agree that having 1) on the main page (or somewhere less prominent in the dashboard Menu > About ?) it can go away entirely.

**Comment by matthewturk** [comment]
I would propose that having the NSF ack somewhere else is fine.  The dashboard menu would be fine.

**Comment by Xarthisius** [comment]
Fixed https://github.com/whole-tale/ngx-dashboard/pull/113
