### ISSUE TITLE
Launch errors

### ISSUE THREAD

**Issue by benmarwick** [whole-tale/whole-tale#7]
I'm attempting to launch some tales, and none are working. I'm seeing:

```
The Tale '' could not be launched !
UnexpectedFrame: UnexpectedFrame(None, 'Received 0x24 while expecting 0xce', None, '')
```

and 

```
The Tale '' could not be launched !
MemoryError: MemoryError()
```

**Comment by MatthewTurk** [comment]
Looks like the nodes were running out of RAM, with too many interested users! @Xarthisius is spinning up more now but it may take a few minutes.  Thanks for the report!

**Comment by Xarthisius** [comment]
One of the services involved in tale instantiation is not cleaning after itself. I'll need to fix that too, before resuming operations.

**Comment by Xarthisius** [comment]
@benmarwick both issues should be fixed now. Let us know if there additional problems
