### ISSUE TITLE
suggest changing 'compose' button to 'new' or 'create'

### ISSUE THREAD

**Issue by ctb** [whole-tale/whole-tale#73]
on the dashboard, I had to go to the help docs to figure out that ‘compose’ button meant ‘create’. maybe change it to ‘new’ or ‘create’?

**Comment by Xarthisius** [comment]
Thanks for the suggestion! It's actually going away entirely as a separate tab/view in the upcoming release and is being replaced by... <cue the drum roll> a "Create New" button!

You can have a sneak peek here: https://dashboard.stage.wholetale.org

**Comment by ctb** [comment]
perfect! thx

**Comment by ThomasThelen** [comment]
Changed and currently running on production!
