### ISSUE TITLE
DOI Resolution User Expectations

### ISSUE THREAD

**Issue by ekansa** [whole-tale/whole-tale#8]
In adding data, there's a search interface that has some user experience troubles.

It would be great to set some user expectations in the interface with regard to DOI resolution. I tried entering in DOIs to different datasets in different repositories, and these did not appear as search results.

Ideally, repository owners should do some content negotiation, but for the time being, some warning to users that only certain DataONE repository DOIs will work.

**Comment by ThomasThelen** [comment]
Thanks for the feedback @ekansa! We've changed the lookup code quite a bit and I'll do some poking around to see if I can reproduce this. I know it's been a while-but if you recall which repositories failed I can look there first!

**Comment by ThomasThelen** [comment]
In the linked issue, I added more information to the registration dialog that outlines where data can be registered from to help avoid confusion.
