### ISSUE TITLE
Citing a Tale's source

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#81]
When I add an external dataset to a Tale, if a citation can be generated we add it to the list of "datasets used" on the Tale,  display on the metadata page (see also https://github.com/whole-tale/dashboard/issues/450), and include as part of the metadata when published.

<img width="666" alt="Screen Shot 2019-12-19 at 9 34 24 AM" src="https://user-images.githubusercontent.com/4334350/71182171-97040e00-2243-11ea-9c79-fdc83223cdbc.png">

 However, when I import an external dataset as a Tale (i.e., into the workspace / via `asTale=true`),  the citation is not added. This makes some sense, since the Tale doesn't "use" the dataset but is "derived from" it. This is also similar to the `copyOfTale` field kept when the user copies an existing tale.

Zenodo supports the DataCite 4.1 relation types (https://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf). `IsDerivedFrom` seems like the best relation.  Dataverse supports additional identifiers without specifying the relation type.

 I think it would make sense to keep, display, and publish this information, but we'll need to decide how to represent it in a way that's useful when published.

**Comment by craig-willis** [comment]
Per discussion today, we're considering the following:

* An external dataset used in a Tale whether manually registered or via AinWT should be represented (conceptually) via the `cites`/`isCitedBy`
* An external dataset, binder or other tale-like object that is brought in via AinWT with `asTale=true` is represented as `IsDerivedFrom`.
* Eventually, if we add support for an associated Github repository, we'd follow Zenodo with `IsSupplementTo`
* If we add support for the associated publication, it would also be `IsSupplementTo`

**Comment by ThomasThelen** [comment]
### Cites
Just to confirm that we want to use datacite and not dc or schema (dc is implicit though the bagit-ro context and we use one word out of schema).

#### DataCite
If we went with DataCite, I believe it would look like the following (we can choose a different namespace, but note that dc is already used for dublin core).
 
```
{
    "@context": [
        "https://w3id.org/bundle/context",
        {
          "DataCite": "https://schema.datacite.org/meta/kernel-4.2/metadata.xsd"
        }
    ],
    name: "my tale",
    "DataCite:relatedIdentifiers": [
      "DataCite:relatedIdentifier": {
        "@id": "<doi>", 
        "DataCite:relatedIdentifierType": "DataCite:DOI",
        "DataCite:relationType": "DataCite:Cites",
      },
      "DataCite:relatedIdentifier": {
        "@id": "<doi2>", 
        "DataCite:relatedIdentifierType": "DataCite:DOI",
        "DataCite:relationType": "DataCite:Cites",
      }
    ],
   .
   .
   .
}
```

#### Dublin Core
We're already importing the dublin core schema though bagit-ro. I _think_ we can use [dc:references](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/references) this way.

```
{
    "@context": [
        "https://w3id.org/bundle/context",
    ],
    name: "my tale",
    "dc:references": ["doi1", "doi2", "doi3", etc],
   .
   .
   .
}
```

#### Schema.org
We can of course also use schema.org to describe the citations with [schema:citation](https://www.schema.org/citation). Note that this property is supposed to be attributed to objects of type CreativeWork, which I don't think we are (I think we're technically an ORE Aggregation). 

```
{
    "@context": [
        "https://w3id.org/bundle/context",
        {
            "schema": "http://schema.org/"
        },
    ],
    name: "my tale",
    "schema:citation": ["doi1", "doi2", "doi3", etc],
   .
   .
   .
}
```

**Comment by ThomasThelen** [comment]
### Derivation Relation

We'll want to decide on whether we track all previous versions of the Tale in this relation. 

If we have the relation `Tale C was made from Tale B, which was made from Tale A`, would we want to keep a complete record of this as `isDerivedFrom: [Tale B, Tale A]` or just point to the most recent with `isDerivedFrom: TaleB`?

In the examples below, I'm assuming that we track all of them.

We'll also want to decide whether Tale A and B are put in the manifest `Datasets` structure. If they are, we can simply reference them in the relations by their ID.

#### DataCite
DataCite, as mentioned above, has the `isDerivedFrom` property. This is used the same way as citations, with only the `DataCite:relationType` changing.

```
{
    "@context": [
        "https://w3id.org/bundle/context",
        {
          "DataCite": "https://schema.datacite.org/meta/kernel-4.2/metadata.xsd"
        }
    ],
    name: "Tale C",
    "DataCite:relatedIdentifiers": [
      "DataCite:relatedIdentifier": {
        "@id": "<doi:TaleA>", 
        "DataCite:relatedIdentifierType": "DataCite:DOI",
        "DataCite:relationType": "DataCite:IsDerivedFrom",
      },
      "DataCite:relatedIdentifier": {
        "@id": "<doi:TaleB>", 
        "DataCite:relatedIdentifierType": "DataCite:DOI",
        "DataCite:relationType": "DataCite:IsDerivedFrom",
      }
    ],
   .
   .
   .
}
```



#### DC & Friends
DC doesn't have a great word for expressing the derivation of a Tale. The closest thing I found was [replaces](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/replaces), which isn't quite what we're after.


The BagIt-RO context also pulls in the prov namespace which has the [wasDerivedFrom](https://www.w3.org/TR/2013/REC-prov-o-20130430/#wasDerivedFrom) property. The issue with this is that it has type constraints that we'd have to work around (should be used on prov:Entity).

#### Schema.org

Schema.org's closest equivilence to a derivation property is [isBasedOn](https://schema.org/isBasedOn). Note that this is supposed to be used on a `CreativeWork`.


```
{
    "@context": [
        "https://w3id.org/bundle/context",
        {
            "schema": "http://schema.org/"
        },
    ],
    name: "my tale",
    "schema:isBasedOn": ["doi:TaleB", "doi:TaleA"],
   .
   .
   .
}
```

**Comment by Xarthisius** [comment]
I took a look what zenodo does with while exporting to different formats. As an example https://zenodo.org/record/3402938 has:

#### Related identifiers
- Compiles 10.5281/zenodo.3381658 (Presentation)
- Identical to https://github.com/rgayler/scorecal_CSCC_2019/tree/v1.2 (Software)
- Source of https://mybinder.org/v2/zenodo/10.5281/zenodo.3402938?urlpath=rstudio/ (Other)

and that exports to

#### DC
```xml
<?xml version='1.0' encoding='utf-8'?>
<oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
  <dc:relation>doi:10.5281/zenodo.3381658</dc:relation>
  <dc:relation>url:https://github.com/rgayler/scorecal_CSCC_2019/tree/v1.2</dc:relation>
  <dc:relation>url:https://mybinder.org/v2/zenodo/10.5281/zenodo.3402938?urlpath=rstudio/</dc:relation>
</oai_dc:dc>
```
Note: relation type is completely missing

#### JSON-LD (schema.org)
Everything is missing...

#### DataCite XML
```xml
<?xml version='1.0' encoding='utf-8'?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.1/metadata.xsd">
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="Compiles" resourceTypeGeneral="Text">10.5281/zenodo.3381658</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="URL" relationType="IsIdenticalTo" resourceTypeGeneral="Software">https://github.com/rgayler/scorecal_CSCC_2019/tree/v1.2</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="URL" relationType="IsSourceOf" resourceTypeGeneral="Other">https://mybinder.org/v2/zenodo/10.5281/zenodo.3402938?urlpath=rstudio/</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="IsVersionOf">10.5281/zenodo.3381640</relatedIdentifier>
  </relatedIdentifiers>
</resource>
```

#### DCAT (whatever it might be)

```xml
<?xml version='1.0' encoding='utf-8'?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:adms="http://www.w3.org/ns/adms#" xmlns:cnt="http://www.w3.org/2011/content#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:dctype="http://purl.org/dc/dcmitype/" xmlns:dcat="http://www.w3.org/ns/dcat#" xmlns:duv="http://www.w3.org/ns/duv#" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:frapo="http://purl.org/cerif/frapo/" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:gsp="http://www.opengis.net/ont/geosparql#" xmlns:locn="http://www.w3.org/ns/locn#" xmlns:org="http://www.w3.org/ns/org#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:prov="http://www.w3.org/ns/prov#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:schema="http://schema.org/" xmlns:skos="http://www.w3.org/2004/02/skos/core#" xmlns:vcard="http://www.w3.org/2006/vcard/ns#" xmlns:wdrs="http://www.w3.org/2007/05/powder-s#">
<rdf:Description rdf:about="https://doi.org/10.5281/zenodo.3402938">
    <dct:relation rdf:resource="https://doi.org/10.5281/zenodo.3381658"/>
    <owl:sameAs rdf:resource="https://github.com/rgayler/scorecal_CSCC_2019/tree/v1.2"/>
    <prov:hadDerivation rdf:resource="https://mybinder.org/v2/zenodo/10.5281/zenodo.3402938?urlpath=rstudio/"/>
    <dct:isVersionOf rdf:resource="https://doi.org/10.5281/zenodo.3381640"/>
  </rdf:Description>
</rdf:RDF>
```

**Comment by ludaesch** [comment]
Not everything is missing! I see a dozen+ namespaces used. Simple questions
such as: 'is wasDerivedFrom transitive or not?' ... Well. More research
needed! (I just looked in PROV constraints but only found rules saying what
isn't transitive.. )

Might need a three-valued modal logic? To deal with: neither confirm nor
deny.

Sorry. Couldn't resist :-)

Will explore this further...



(sent from my mobile phone)

**Comment by Xarthisius** [comment]
> Not everything is missing! I see a dozen+ namespaces used. Simple questions such as: 'is wasDerivedFrom transitive or not?' ... Well. More research needed! 

If you're referring to my comment about JSON-LD (schema.org) exported from zenodo record, what I meant is the information about related identifiers is missing.
