### ISSUE TITLE
Access data from jupyter notebook

### ISSUE THREAD

**Issue by IbtihalFerwana** [whole-tale/whole-tale#86]
Hello, 

I have my data uploaded to Zenodo, and got its DOI to my tale Data files

I have a notebook in "interact", what directory/path I should use to access my data?
I tried "Data\.." but did not work

any hints?

**Comment by Xarthisius** [comment]
Hi @IbtihalFerwana 
with respect to the directory that notebook uses as a working directory it's going to be in `../data`, e.g. in your `Analysis_diseases` Tale you've got:

```bash
$ ls -lR ../data
../data:
total 1
drwxr-xr-x 2 root root 10700845 Nov 17 21:42 'Diseases Data for Cleaning_ver_1'

'../data/Diseases Data for Cleaning_ver_1':
total 2
-rw-r--r-- 1 root root 3463284 Nov 17 21:42 hepatitis.csv
-rw-r--r-- 1 root root 5053296 Nov 17 21:42 measles.csv
-rw-r--r-- 1 root root 2184265 Nov 17 21:42 mumps.csv

```

**Comment by IbtihalFerwana** [comment]
Thanks! 
I found it now
