### ISSUE TITLE
Publishing Tale

### ISSUE THREAD

**Issue by IbtihalFerwana** [whole-tale/whole-tale#87]
I connected my Zenodo account, 
![image](https://user-images.githubusercontent.com/41843953/99595607-a4c59480-29ba-11eb-843a-c028258480f7.png)

what I'm supposed to see?
How to know it is published?

**Comment by IbtihalFerwana** [comment]
I keep getting this:
![image](https://user-images.githubusercontent.com/41843953/99595765-e22a2200-29ba-11eb-84fc-481f88742a0e.png)

**Comment by ThomasThelen** [comment]
Apologies for the issue; something looks off here and it must be a bug.
Can you disconnect your Zenodo account and re-connect? You shouldn't be seeing both "Connect Account" and the "Disconnect" buttons at the same time on the Settings page. Once connecting the account you _should_ see a different popup when re-clicking the publish button in the dropdown menu.

**Comment by IbtihalFerwana** [comment]
I'm not choosing the sandbox

**Comment by Xarthisius** [comment]
I can reproduce that behavior. We'll investigate and fix this as soon as possible.

**Comment by IbtihalFerwana** [comment]
Ok. Thanks a lot!

**Comment by Xarthisius** [comment]
> Ok. Thanks a lot!

It was disabled in the setup, but it should be working now.
