### ISSUE TITLE
Tale Illustrations from URI?

### ISSUE THREAD

**Issue by bocinsky** [whole-tale/whole-tale#9]
I was trying to add my own illustration, but the dashboard doesn't seem to allow me to add it. The image keeps reverting to one of the stock images. Tale ID: 59a9b9e946a83d0001ab6704

**Comment by Xarthisius** [comment]
Thanks for the report. We believe that issue is now fixed. (https://github.com/whole-tale/dashboard/commit/563005e170c96d7fbf7c6cf1dc628c911144beb5)
