### ISSUE TITLE
Mark all as read color

### ISSUE THREAD

**Issue by matthewturk** [whole-tale/whole-tale#92]
Would it be possible to get the "Mark all as read" button on notifications set to a slightly more eye-catching color?  On mine it was white with a box, which didn't snag my attention.

**Comment by Xarthisius** [comment]
![dash](https://user-images.githubusercontent.com/352673/106915837-1fee3b00-66cc-11eb-9bea-cc6378a2b718.png)

This is current vs upcoming view of notification panel. Does the new "Acknowledge All" looks OK, or does you comment still stands?

**Comment by matthewturk** [comment]
I would say it still stands, since it's a shade of the background, rather
than a different color.  Even a border would help I think.
